import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

import sqlite3
con = sqlite3.connect('ppdb.db')
cur = con.cursor()

from login import logIn

class DaftarSekolah(QWidget):
    def __init__(self):        
        super().__init__()        
        self.setWindowTitle("Daftar Sekolah")
        self.setGeometry(0, 0, 891, 496)
        cwa = self.frameGeometry()
        cwc = QDesktopWidget().availableGeometry().center()
        cwa.moveCenter(cwc)
        self.move(cwa.topLeft())
        self.UI()
        self.show()
        
    def UI(self):
        self.setupUi()
        self.retranslateUi()
        
    def closeEvent(self, event):
        self.mainwin = logIn()
        
    def setupUi(self):
        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMaximumSize(QtCore.QSize(550, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignTop)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setObjectName("gridLayout")
        self.npsn = QtWidgets.QLabel(self.widget_3)
        self.npsn.setMinimumSize(QtCore.QSize(50, 30))
        self.npsn.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.npsn.setFont(font)
        self.npsn.setObjectName("npsn")
        self.gridLayout.addWidget(self.npsn, 2, 0, 1, 1)
        self.telp = QtWidgets.QLabel(self.widget_3)
        self.telp.setMinimumSize(QtCore.QSize(120, 30))
        self.telp.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.telp.setFont(font)
        self.telp.setObjectName("telp")
        self.gridLayout.addWidget(self.telp, 6, 0, 1, 1)
        self.lineEdit_telp = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_telp.setMinimumSize(QtCore.QSize(400, 30))
        self.lineEdit_telp.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_telp.setFont(font)
        self.lineEdit_telp.setObjectName("lineEdit_telp")
        self.gridLayout.addWidget(self.lineEdit_telp, 7, 0, 1, 1)
        self.lineEdit_nama = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_nama.setMinimumSize(QtCore.QSize(400, 30))
        self.lineEdit_nama.setMaximumSize(QtCore.QSize(400, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_nama.setFont(font)        
        self.lineEdit_nama.setObjectName("lineEdit_nama")
        self.gridLayout.addWidget(self.lineEdit_nama, 1, 0, 1, 1)
        self.lineEdit_npsn = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_npsn.setMinimumSize(QtCore.QSize(400, 30))
        self.lineEdit_npsn.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_npsn.setFont(font)        
        self.lineEdit_npsn.setObjectName("lineEdit_npsn")
        self.gridLayout.addWidget(self.lineEdit_npsn, 3, 0, 1, 1)
        self.lineEdit_psw = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_psw.setMinimumSize(QtCore.QSize(400, 30))
        self.lineEdit_psw.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_psw.setFont(font)        
        self.lineEdit_psw.setObjectName("lineEdit_psw")
        self.gridLayout.addWidget(self.lineEdit_psw, 5, 0, 1, 1)
        self.alamat = QtWidgets.QLabel(self.widget_3)
        self.alamat.setMinimumSize(QtCore.QSize(120, 30))
        self.alamat.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.alamat.setFont(font)
        self.alamat.setObjectName("alamat")
        self.gridLayout.addWidget(self.alamat, 10, 0, 1, 1)
        self.lineEdit_alamat = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_alamat.setMinimumSize(QtCore.QSize(400, 30))
        self.lineEdit_alamat.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_alamat.setFont(font)
        self.lineEdit_alamat.setObjectName("lineEdit_alamat")
        self.gridLayout.addWidget(self.lineEdit_alamat, 11, 0, 1, 1)
        self.nmsekolah = QtWidgets.QLabel(self.widget_3)
        self.nmsekolah.setMinimumSize(QtCore.QSize(110, 30))
        self.nmsekolah.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.nmsekolah.setFont(font)
        self.nmsekolah.setObjectName("nmsekolah")
        self.gridLayout.addWidget(self.nmsekolah, 0, 0, 1, 1)
        self.email = QtWidgets.QLabel(self.widget_3)
        self.email.setMinimumSize(QtCore.QSize(60, 30))
        self.email.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.email.setFont(font)
        self.email.setObjectName("email")
        self.gridLayout.addWidget(self.email, 8, 0, 1, 1)
        self.psw = QtWidgets.QLabel(self.widget_3)
        self.psw.setMinimumSize(QtCore.QSize(80, 30))
        self.psw.setMaximumSize(QtCore.QSize(110, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.psw.setFont(font)
        self.psw.setObjectName("psw")
        self.gridLayout.addWidget(self.psw, 4, 0, 1, 1)
        self.lineEdit_email = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_email.setMinimumSize(QtCore.QSize(400, 30))
        self.lineEdit_email.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_email.setFont(font)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.gridLayout.addWidget(self.lineEdit_email, 9, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget_3)
        self.pushButton.setMinimumSize(QtCore.QSize(400, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(400, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 13, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.verticalLayout.addWidget(self.widget_2)
        
        self.setLayout(self.verticalLayout)

    def retranslateUi(self):
        self.label.setText("FORM PENDAFTARAN SEKOLAH")
        self.nmsekolah.setText("Nama Sekolah :")
        self.npsn.setText("NPSN :")
        self.psw.setText("Password :")
        self.telp.setText("Nomor Telepon :")
        self.email.setText("E-mail :")
        self.alamat.setText("Alamat Sekolah :")
        self.pushButton.setText("Daftar")
        self.pushButton.clicked.connect(self.addSkul)

    def addSkul(self):
        nama_sekolah = self.lineEdit_nama.text()
        npsn = self.lineEdit_npsn.text()
        password = self.lineEdit_psw.text()
        nomor_telepon = self.lineEdit_telp.text()
        email = self.lineEdit_email.text()
        alamat_sekolah = self.lineEdit_alamat.text()

        def kosong():
            nama_sekolah = self.lineEdit_nama.setText("")
            npsn = self.lineEdit_npsn.setText("")
            password = self.lineEdit_psw.setText("")
            nomor_telepon = self.lineEdit_telp.setText("")
            email = self.lineEdit_email.setText("")
            alamat_sekolah = self.lineEdit_alamat.setText("")
            
        if nama_sekolah and npsn and password != "":
            try:
                query = "INSERT INTO tb_addskul (nama, npsn, pass, telp, email, alamat) VALUES(?,?,?,?,?,?)"
                cur.execute(query, (nama_sekolah, npsn, password, nomor_telepon, email, alamat_sekolah))
                con.commit()
                QMessageBox.information(self, "Berhasil", "Data sekolah berhasil disimpan")
                kosong()
                self.close()
                self.mainwin = logIn()
            except:
                QMessageBox.information(self, "Perhatian", "Data sekolah tidak berhasil disimpan")
        else:
            QMessageBox.warning(self, "Perhatian", "Data tidak boleh kosong")

def main():
    APP = QApplication(sys.argv)
    window = DaftarSekolah()
    sys.exit(APP.exec())
    
if __name__ == '__main__':
    main()