import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *



import sqlite3
con = sqlite3.connect('ppdb.db')
cur = con.cursor()

class editData(QWidget):    
    def __init__(self, ) :
        super().__init__()
        self.setWindowTitle("Form Edit Data Siswa")
        self.setGeometry(0, 0, 891, 496)
        cwa = self.frameGeometry()
        cwc = QDesktopWidget().availableGeometry().center()
        cwa.moveCenter(cwc)
        self.move(cwa.topLeft())
        self.UI()
        self.show()
        
    def UI(self):
        self.setupUi()
        self.retranslateUi()

    def closeEvent(self, event):
        from semuasiswa import semuaSiswa
        self.mainwin = semuaSiswa()

    def setupUi(self):
        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 60))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.backBtn = QtWidgets.QToolButton(self.widget_3)
        self.backBtn.setMinimumSize(QtCore.QSize(72, 25))
        self.backBtn.setMaximumSize(QtCore.QSize(73, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backBtn.setFont(font)
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout_3.addWidget(self.backBtn, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout.addWidget(self.widget_3, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setMinimumSize(QtCore.QSize(500, 35))
        self.label.setMaximumSize(QtCore.QSize(500, 35))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.horizontalLayout.addWidget(self.widget_4, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.widget_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 761, 778))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_5 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_16 = QtWidgets.QWidget(self.widget_5)
        self.widget_16.setObjectName("widget_16")
        self.formLayout_9 = QtWidgets.QFormLayout(self.widget_16)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_5 = QtWidgets.QLabel(self.widget_16)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.nodaftarEdit = QtWidgets.QLineEdit(self.widget_16)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nodaftarEdit.setFont(font)
        self.nodaftarEdit.setObjectName("nodaftarEdit")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nodaftarEdit)
        self.label_4 = QtWidgets.QLabel(self.widget_16)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_16)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.verticalLayout_3.addWidget(self.widget_16)
        self.label_2 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.widget_5, 0, QtCore.Qt.AlignTop)
        self.widget_6 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_6.setObjectName("widget_6")
        self.formLayout = QtWidgets.QFormLayout(self.widget_6)
        self.formLayout.setObjectName("formLayout")
        self.nm_siswaLbl = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nm_siswaLbl.setFont(font)
        self.nm_siswaLbl.setObjectName("nm_siswaLbl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nm_siswaLbl)
        self.nm_siswaEdit = QtWidgets.QLineEdit(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nm_siswaEdit.setFont(font)
        self.nm_siswaEdit.setObjectName("nm_siswaEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nm_siswaEdit)
        self.nisn_siswaLbl = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nisn_siswaLbl.setFont(font)
        self.nisn_siswaLbl.setObjectName("nisn_siswaLbl")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nisn_siswaLbl)
        self.nisn_siswaEdit = QtWidgets.QLineEdit(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nisn_siswaEdit.setFont(font)
        self.nisn_siswaEdit.setObjectName("nisn_siswaEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nisn_siswaEdit)
        self.alamat_siswaLbl = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.alamat_siswaLbl.setFont(font)
        self.alamat_siswaLbl.setObjectName("alamat_siswaLbl")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.alamat_siswaLbl)
        self.alamat_siswaEdit = QtWidgets.QLineEdit(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.alamat_siswaEdit.setFont(font)
        self.alamat_siswaEdit.setObjectName("alamat_siswaEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.alamat_siswaEdit)
        self.tptlahir_siswaLbl = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tptlahir_siswaLbl.setFont(font)
        self.tptlahir_siswaLbl.setObjectName("tptlahir_siswaLbl")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.tptlahir_siswaLbl)
        self.tptlahir_siswaEdit = QtWidgets.QLineEdit(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tptlahir_siswaEdit.setFont(font)
        self.tptlahir_siswaEdit.setObjectName("tptlahir_siswaEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.tptlahir_siswaEdit)
        self.tgllahir_siswaLbl = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tgllahir_siswaLbl.setFont(font)
        self.tgllahir_siswaLbl.setObjectName("tgllahir_siswaLbl")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.tgllahir_siswaLbl)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.jk_siswaLbl = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.jk_siswaLbl.setFont(font)
        self.jk_siswaLbl.setObjectName("jk_siswaLbl")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.jk_siswaLbl)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.agama_siswaLbl = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.agama_siswaLbl.setFont(font)
        self.agama_siswaLbl.setObjectName("agama_siswaLbl")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.agama_siswaLbl)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.verticalLayout.addWidget(self.widget_6)
        self.widget_11 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.verticalLayout.addWidget(self.widget_11)
        self.widget_7 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_7.setObjectName("widget_7")
        self.formLayout_3 = QtWidgets.QFormLayout(self.widget_7)
        self.formLayout_3.setObjectName("formLayout_3")
        self.nama_sekolahLbl = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nama_sekolahLbl.setFont(font)
        self.nama_sekolahLbl.setObjectName("nama_sekolahLbl")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nama_sekolahLbl)
        self.nama_sekolahEdit = QtWidgets.QLineEdit(self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nama_sekolahEdit.setFont(font)
        self.nama_sekolahEdit.setObjectName("nama_sekolahEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nama_sekolahEdit)
        self.alamat_sekolahLbl = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.alamat_sekolahLbl.setFont(font)
        self.alamat_sekolahLbl.setObjectName("alamat_sekolahLbl")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.alamat_sekolahLbl)
        self.alamat_sekolahEdit = QtWidgets.QLineEdit(self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.alamat_sekolahEdit.setFont(font)
        self.alamat_sekolahEdit.setObjectName("alamat_sekolahEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.alamat_sekolahEdit)
        self.verticalLayout.addWidget(self.widget_7)
        self.widget_8 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.verticalLayout.addWidget(self.widget_8)
        self.widget_9 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_9.setObjectName("widget_9")
        self.formLayout_7 = QtWidgets.QFormLayout(self.widget_9)
        self.formLayout_7.setObjectName("formLayout_7")
        self.nama_ayahLbl = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nama_ayahLbl.setFont(font)
        self.nama_ayahLbl.setObjectName("nama_ayahLbl")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nama_ayahLbl)
        self.nama_ayahEdit = QtWidgets.QLineEdit(self.widget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nama_ayahEdit.setFont(font)
        self.nama_ayahEdit.setObjectName("nama_ayahEdit")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nama_ayahEdit)
        self.nama_ibuLbl = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nama_ibuLbl.setFont(font)
        self.nama_ibuLbl.setObjectName("nama_ibuLbl")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nama_ibuLbl)
        self.penghasilan_ortuLbl = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.penghasilan_ortuLbl.setFont(font)
        self.penghasilan_ortuLbl.setObjectName("penghasilan_ortuLbl")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.penghasilan_ortuLbl)
        self.telp_ortuLbl = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.telp_ortuLbl.setFont(font)
        self.telp_ortuLbl.setObjectName("telp_ortuLbl")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.telp_ortuLbl)
        self.penghasilan_ortuEdit = QtWidgets.QLineEdit(self.widget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.penghasilan_ortuEdit.setFont(font)
        self.penghasilan_ortuEdit.setObjectName("penghasilan_ortuEdit")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.penghasilan_ortuEdit)
        self.nama_ibuEdit = QtWidgets.QLineEdit(self.widget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nama_ibuEdit.setFont(font)
        self.nama_ibuEdit.setObjectName("nama_ibuEdit")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nama_ibuEdit)
        self.telp_ortuEdit = QtWidgets.QLineEdit(self.widget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.telp_ortuEdit.setFont(font)
        self.telp_ortuEdit.setObjectName("telp_ortuEdit")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.telp_ortuEdit)
        self.verticalLayout.addWidget(self.widget_9)
        self.widget_10 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.simpanBtn = QtWidgets.QPushButton(self.widget_10)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.simpanBtn.setFont(font)
        self.simpanBtn.setObjectName("simpanBtn")
        self.horizontalLayout_5.addWidget(self.simpanBtn)
        self.batalBtn = QtWidgets.QPushButton(self.widget_10)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.batalBtn.setFont(font)
        self.batalBtn.setObjectName("batalBtn")
        self.horizontalLayout_5.addWidget(self.batalBtn)
        self.verticalLayout.addWidget(self.widget_10)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout_2.addWidget(self.widget_2)
        
        self.nodaftarEdit.setDisabled(True)
        self.setLayout(self.verticalLayout_2)
        
    def retranslateUi(self,):
        self.backBtn.setText("Kembali")
        self.backBtn.clicked.connect(self.kembali)
        self.label.setText("UBAH DATA SISWA")
        self.label_5.setText("No Pendaftaran")
        self.label_4.setText("Tanggal Daftar")
        self.lineEdit_2.setText("dd/mm/yyyy")
        self.label_2.setText("DATA SISWA")
        self.nm_siswaLbl.setText("Nama Lengkap")
        self.nisn_siswaLbl.setText("NISN")
        self.alamat_siswaLbl.setText("Alamat Lengkap")
        self.tptlahir_siswaLbl.setText("Tempat Lahir")
        self.tgllahir_siswaLbl.setText("Tanggal Lahir")
        self.lineEdit_3.setText("dd/mm/yyyy")
        self.jk_siswaLbl.setText("Jenis Kelamin")
        self.agama_siswaLbl.setText("Agama")
        self.label_3.setText("DATA ASAL SEKOLAH")
        self.nama_sekolahLbl.setText("Nama Sekolah")
        self.alamat_sekolahLbl.setText("Alamat Sekolah")
        self.label_12.setText("DATA ORANG TUA")
        self.nama_ayahLbl.setText("Nama Ayah/Wali")
        self.nama_ibuLbl.setText("Nama Ibu")
        self.penghasilan_ortuLbl.setText("Penghasilan Orang Tua")
        self.telp_ortuLbl.setText("Nomo Telepon/HP Orang Tua")
        self.simpanBtn.setText("Simpan")
        self.simpanBtn.clicked.connect(self.simpanData)
        self.batalBtn.setText("Batal")
        self.batalBtn.clicked.connect(self.kembali)
        
    def simpanData(self):
        id = self.nodaftarEdit.text()
        tanggal_daftar = self.lineEdit_2.text()
        nama_siswa = self.nm_siswaEdit.text()
        nisn = self.nisn_siswaEdit.text()
        adres_siswa = self.alamat_siswaEdit.text()
        tmpt_lahir = self.tptlahir_siswaEdit.text()
        tanggal_lahir = self.lineEdit_3.text()          
        jk = self.lineEdit_4.text()
        agama_siswa = self.lineEdit_5.text()
        asal_sklh = self.nama_sekolahEdit.text()
        adres_sekolah = self.alamat_sekolahEdit.text()
        nm_ayah = self.nama_ayahEdit.text()
        nm_ibu = self.nama_ibuEdit.text()
        penghasilan = self.penghasilan_ortuEdit.text()
        hp_ortu = self.telp_ortuEdit.text()

        if (id !=""):
            try:
                # Update data di tabel tb_addsiswa
                query_update_addsiswa = "UPDATE tb_addsiswa SET tgl_daftar=?, nama_lengkap=?, nisn_siswa=?, alamat_siswa=?, tempat_lahir=?, tgl_lahir=?, gender=?, agama=?, asal_sekolah=?, alamat_sekolah=?, nama_ayah=?, nama_ibu=?, penghasilan_ortu=?, telp_ortu=? WHERE no_daftar=?"
                cur.execute(query_update_addsiswa, (tanggal_daftar, nama_siswa, int(nisn), adres_siswa, tmpt_lahir, tanggal_lahir, jk, agama_siswa, asal_sklh, adres_sekolah, nm_ayah, nm_ibu, int(penghasilan), int(hp_ortu), id))
                con.commit()                
                QMessageBox.information(self, "Berhasil", "Data siswa berhasil disimpan")
                self.close()
                
            except Exception as e:
                QMessageBox.warning(self, "Perhatian", "Data siswa tidak berhasil disimpan")
                print("Error:", str(e))
        else:
            QMessageBox.warning(self, "Perhatian", "Data tidak boleh kosong")
            
    def kembali(self):
        self.close()
     
def main():
    APP = QApplication(sys.argv)
    window = editData()
    window.show()
    sys.exit(APP.exec())
    
if __name__ == '__main__':
    main()